### ISSUE TITLE
View Status Page Link doesn't seem to work in version 0.6.1

### ISSUE THREAD

**Issue by luckymike** [ks888/LambStatus#101]
Just installed 0.6.1 after using 0.5.0 successfully. The View Status Page link in the Admin header seems to be broken.

**Comment by ks888** [comment]
Thank you for reporting. Somehow I can't reproduce the bug in my env. Can you tell me more details? These info may be helpful:
* How the left part of the header looks like? It should be '[Your service name] Status Admin'.
<img width="275" alt="screen shot 2018-02-24 at 10 44 22" src="https://user-images.githubusercontent.com/8448120/36624223-cb97397a-194f-11e8-949d-41e6575341c4.png">

* Also, how the right part of the header looks like? It looks something like '[Your user name] v'.
<img width="249" alt="screen shot 2018-02-24 at 10 46 40" src="https://user-images.githubusercontent.com/8448120/36624256-2b20e634-1950-11e8-84a8-c936f8d21aa2.png">

* What if you click the 'View Status Page' link? Visit invalid url like 'undefined'? Or can't click?
* What happens if you use a different browser or private/incognito mode?

**Comment by luckymike** [comment]
Nevermind, my stack wasn't complete yet. Works now.

**Comment by luckymike** [comment]
If there's an easy way to delay the admin email until the end of the stack build, that might be good to avoid this confusion.
