### ISSUE TITLE
Getting Access Denied after Deployment

### ISSUE THREAD

**Issue by rainerCH** [ks888/LambStatus#153]
Hi

i am installing LambStatus with your "getting started" guide. I am receiving the E-Mail after ~15 Minutes but get an Access Denied Error from S3. Do i have to tweak the S3 Bucket after installation?

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>`

Thank you!

**Comment by Gareth10jones** [comment]
I am experiencing the same issue, have waited approx 1 hour after install..

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>XXX</RequestId>
<HostId>
XXX
</HostId>
</Error>`

**Comment by ks888** [comment]
Please check the doc: https://lambstatus.github.io/get-started#troubleshooting

**Comment by elemenoeric** [comment]
The doc just says to wait 10-20 minutes.  I'm having the same problem 40 minutes after the deployment completed.  I checked the S3 permissions, and the static files including the index.html are viewable only by owner.  I'm probably not the owner--I'm not the only engineer on this project, although I have elevated permissions.  Are you assuming that only the owner will access the site?

I went in to S3 and made the index.html for the admin page public, and then I could load it via the emailed link, but of course the page is broken because all the other files [javascript, etc.] are still private.  Do I need to make them all public in order for the dashboard to be usable?

Thanks!

**Comment by ks888** [comment]
LambStatus uses [the Origin Access Identity](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html) for S3 access. So it's ok that the S3 buckets are not public.

Do you still have a problem? If yes, check if you have any items on the Origin Access Identity page below:
https://console.aws.amazon.com/cloudfront/home#oai:

**Comment by rainerCH** [comment]
@elemenoeric i just checked the other day and then it worked.

**Comment by elemenoeric** [comment]
Indeed, it's started working for me now.  I thought cloudfront must be done already because the redirect worked when I made index.html world-readable, but apparently there's more going on than that, and waiting yet longer did the trick.  Sorry about the noise, and thanks for your help!
